feat: make the prefix in the solution optional across resource names
terraform-ibm-modules/terraform-ibm-account-infrastructure-base pull request #110
Opened 2024-04-19 23:10 UTC by MatthewLemmond

### Description
Allows a consumer to provide either:
* prefix + name of a resource / group
* name of a resource / group

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-04-19 23:10 UTC, MatthewLemmond commented
/run pipeline

2024-04-22 14:06 UTC, MatthewLemmond commented
/run pipeline

2024-04-23 08:42 UTC, ocofaigh requested changes
@MatthewLemmond please update all variable descriptions that would not be impacted if a prefix value was passed. If you take a look at https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/pull/99 for example, you can see we added the text `If prefix input variable is passed then it will get prefixed infront of the value in the format of '<prefix>-value'` to all of them.

2024-04-23 08:42 UTC, ocofaigh commented on solutions/account-infrastructure-base/variables.tf
>    description = "Prefix to append to all resources created by this solution."
Can you add `(Optional)` to the start of this descrption?

2024-04-23 18:32 UTC, MatthewLemmond commented
/run pipeline

2024-04-23 18:44 UTC, MatthewLemmond commented
> @MatthewLemmond can you confirm if did a test not passing prefix to confirm this works as expected?

[here](https://github.com/terraform-ibm-modules/terraform-ibm-account-infrastructure-base/actions/runs/8805467544/job/24168251303) is a run that didn't have a prefix provided and it successfully created the resource group without a prefix (failed due to name conflict on the bucket) so this serves as a proof of concept that it's working without the prefix being passed in

2024-04-23 18:45 UTC, MatthewLemmond commented
/run pipeline

2024-04-24 15:45 UTC, MatthewLemmond commented
/run pipeline

2024-04-26 15:39 UTC, vburckhardt commented
/run pipeline

2024-04-29 15:02 UTC, MatthewLemmond commented on solutions/account-infrastructure-base/variables.tf
> +  description = "The name of the management resource group to create. If `var.prefix` is provided then it will be prefixed on the name in the format of `<var.prefix>-<var.management_resource_group_na
removed the 'var.' when referencing variables from the descriptions

2024-04-30 11:05 UTC, vburckhardt approved these changes

2024-04-30 11:06 UTC, merged

2024-04-30 11:07 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.4.0 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-account-infrastructure-base/releases/tag/v1.4.0)
- `v1.4.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: