Update variables.tf - content edits part 1
terraform-ibm-modules/terraform-ibm-account-infrastructure-base pull request #134
Opened 2024-05-16 22:18 UTC by addison-martin1

### Description

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-05-20 13:16 UTC, SirSpidey requested changes
couple of small nits

2024-05-20 15:32 UTC, addison-martin1 commented on solutions/account-infrastructure-base/variables.tf
> +  description = "Region to provision the Object Storage resources created by this solution. Only required if `provision_atracker_cos` is true."
@SirSpidey Thank you for the review, Allen! Made updates.

2024-05-20 15:55 UTC, MatthewLemmond commented
/run pipeline

2024-05-20 19:01 UTC, MatthewLemmond commented
/run pipeline

2024-05-20 20:51 UTC, MatthewLemmond approved these changes

2024-05-20 21:17 UTC, MatthewLemmond commented
/run pipeline

2024-05-21 12:27 UTC, toddgiguere commented
/run pipeline

2024-05-21 13:32 UTC, SirSpidey approved these changes
👍

2024-05-21 13:48 UTC, merged