refactor: added additional prefix validation
terraform-ibm-modules/terraform-ibm-account-infrastructure-base pull request #246
Opened 2024-11-14 18:44 UTC by kierramarie

### Description

Added additional prefix validation to check more than length.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-11-14 19:17 UTC, kierramarie commented
/run pipeline

2024-11-14 19:41 UTC, kierramarie commented
/run pipeline

2024-11-14 21:15 UTC, kierramarie commented
/run pipeline

2024-11-15 16:04 UTC, kierramarie commented
/run pipeline

2024-11-20 04:47 UTC, alex-reiff approved these changes

2024-12-09 17:09 UTC, kierramarie commented
/run pipeline

2024-12-11 15:52 UTC, kierramarie commented
/run pipeline

2025-01-06 21:12 UTC, kierramarie commented
/run pipeline

2025-01-21 21:48 UTC, kierramarie commented
/run pipeline

2025-02-06 17:07 UTC, MatthewLemmond requested changes
There is currently a conflict in the ibm_catalog.json that needs to be addressed

2025-02-06 17:07 UTC, MatthewLemmond commented on solutions/account-infrastructure-base/variables.tf
> +        can(regex("^([a-z]|[a-z][-a-z0-9]{0,14}[a-z0-9])$|^$", var.prefix)),
Need to add the {0,N} constraint on the first `all lowercase` check, also can you update the comment above this to show where the 16 is coming from? Currently we're restricting to 13 characters long so we should document here where the restriction change is coming from.

2025-02-06 17:07 UTC, MatthewLemmond commented on solutions/account-infrastructure-base/variables.tf
> +        length(regexall("^.*--.*", var.prefix)) == 0
Add a note to the error message clarifying that double hyphens are not allowed in prefixes

2025-02-06 17:31 UTC, kierramarie commented
/run pipeline

2025-02-10 16:40 UTC, kierramarie commented
/run pipeline

2025-02-10 18:43 UTC, MatthewLemmond approved these changes

2025-02-11 19:00 UTC, merged

2025-02-11 19:01 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.18.2 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-account-infrastructure-base/releases/tag/v1.18.2)
- `v1.18.2`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: