feat: make atracker + cos opt-in feature
terraform-ibm-modules/terraform-ibm-account-infrastructure-base pull request #87
Opened 2024-03-27 01:13 UTC by MatthewLemmond

### Description
This PR updates the root of the module to make the atracker route and bucket for log storage optional based on a variable provided by the consumer

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-03-27 01:14 UTC, MatthewLemmond commented
/run pipeline

2024-03-27 13:55 UTC, ocofaigh requested changes
@MatthewLemmond left one comment. Can you also maybe update some of the variable descriptions, as some of them are now only required if `provision_atracker_cos` is set to true.

2024-03-27 13:55 UTC, ocofaigh commented on tests/pr_test.go
> +func TestRunDAWithObs(t *testing.T) {
No need to create a new test. Just set `provision_atracker_cos` to true in the current test

2024-03-27 21:06 UTC, MatthewLemmond commented
/run pipeline

2024-03-28 09:16 UTC, ocofaigh commented
@MatthewLemmond You prob need to skip upgrade test:
```
│ Error: Value for undeclared variable
│ 
│ A variable named "provision_atracker_cos" was assigned on the command line,
│ but the root module does not declare a variable of that name. To use this
│ value, add a "variable" block to the configuration.
╵}
```

2024-03-28 15:40 UTC, MatthewLemmond commented
/run pipeline

2024-03-29 13:45 UTC, vburckhardt approved these changes

2024-03-29 13:45 UTC, merged

2024-03-29 13:46 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-account-infrastructure-base/releases/tag/v1.2.0)
- `v1.2.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: